---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  chart:
    spec:
      chart: plex
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    timezone: "Europe/Warsaw"
    persistence:
      config:
        enabled: true
        claimName: "openebs-hostpath-plex-config-pvc"
      transcode:
        enabled: true
        claimName: "openebs-hostpath-plex-transcode-pvc"
      data:
        enabled: true
        claimName: "nfs-media-pvc"
  interval: 10m0s

