---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-plex-config-pv
  namespace: media
spec:
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: media
    name: nfs-plex-config-pvc
  storageClassName: nfs
  nfs:
    server: 192.168.0.13
    path: "/mnt/Internal/Test/AppData/Plex/Config"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-plex-config-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 512Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-plex-transcode-pv
  namespace: media
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: media
    name: nfs-plex-transcode-pvc
  storageClassName: nfs
  nfs:
    server: 192.168.0.13
    path: "/mnt/Internal/Test/AppData/Plex/Transcode"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-plex-transcode-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 20Gi