---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs
  namespace: storage
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: openebs
      version: 2.4.2
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: flux-system
  values:
    localprovisioner:
      enabled: true
      basePath: "/var/openebs/local"
  interval: 10m0s

