---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: plex-route
  namespace: media
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`plex.localhost`)
      services:
        - kind: Service
          name: plex
          namespace: media
          passHostHeader: false
          port: 32400