---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: qbittorrent
      version: 7.1.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    env:
      TZ: Europe/Warsaw
      PUID: 1000
      PGID: 1000
    persistence:
      config:
        enabled: true
        existingClaim: "openebs-hostpath-qbittorrent-config-pvc"
      downloads:
        enabled: true
        mountPath: "/downloads"
        existingClaim: "nfs-downloads-pvc"
  interval: 10m0s

