---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: flux-system
spec:
  chart:
    spec:
      chart: sonarr
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
  interval: 10m0s

