---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  chart:
    spec:
      chart: sonarr
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    env:
      TZ: Europe/Warsaw
      PUID: 1001
      PGID: 1001
    persistence:
      config:
        enabled: true
        existingClaim: "nfs-sonarr-config-pvc"
    additionalVolumeMounts:
    - name: "downloads"
      mountPath: "/downloads"
    additionalVolumes:
    - name: "downloads"
      persistentVolumeClaim:
        claimName: "nfs-downloads-pvc"
  interval: 10m0s

