---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-sonarr-config-pv
spec:
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: default
    name: nfs-sonarr-config-pvc
  storageClassName: nfs
  nfs:
    server: 192.168.0.13
    path: "/mnt/Internal/Test/Sonarr"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-sonarr-config-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 512Mi