---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: gitea-route
  namespace: programming
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`git.zolnierowi.cz`)
      services:
        - kind: Service
          name: gitea-http
          namespace: programming
          passHostHeader: true
          port: 3000