---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: bazarr-route
  namespace: media
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`jackett.zolnierowi.cz`)
      services:
        - kind: Service
          name: jackett
          namespace: media
          passHostHeader: true
          port: 9117