---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: qbittorrent-route
  namespace: media
spec:
  entryPoints:
    - websecure
  tls:
    store: 
      name: default
  routes:
    - kind: Rule
      match: Host(`torrent.zolnierowi.cz`)
      services:
        - kind: Service
          name: qbittorrent
          namespace: media
          passHostHeader: false
          port: 8080