---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: sonarr-route
  namespace: media
spec:
  entryPoints:
    - websecure
  tls:
    store: 
      name: default
  routes:
    - kind: Rule
      match: Host(`sonarr.zolnierowi.cz`)
      services:
        - kind: Service
          name: sonarr
          namespace: media
          passHostHeader: true
          port: 8989