apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-staging-cert
spec:
  secretName: letsencrypt-staging-cert-secret
  dnsNames:
    - "*.zolnierowi.cz"
  issuerRef:
    name: letsencrypt-staging
    kind: Issuer
    group: cert-manager.io