apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cert-manager-cloudflare
spec:
  encryptedData:
    api-token: AgA1YCPf81CjRO0G8OsKYbcQMKIUm6cJa7RGhuznTAnkN1wQVwcgD60f1RmSGV7ynE+IPNcH/z5l8/NjAzzyq1Un+kFEX9nWflkzBI/c0376sbdEjVqcdyn8gZeguH8pN7CUNJXKIjsno0ib9xEXnSSU/YqN5HRUl2EOvCET81p9JG0/DQDTIDJfgOoK69eBkcmM/5dLwJneOVgSE9kdW03n3wC6LPmQa1fW3PdqFLGCrX5/pX+dxEfvoUM1/Tpq4BirALBqhH8Kw3Paeh8DyiEhAQ2FFi/ECCxxQuRsrcKb8oG0ntxaZm3WrhGyNUXYKVJ0l+kNs7/MGczSb9KfhekwUZZbpW9k0WG0zwtnFylrnDUfISD0tfpx3Br3pxjqLyUWl+mYUXnGR5G5U0WM9yTCXvFjv6LF8uLdkm6PPU+JTlI+Kr/54YjB+Y88wawrPvtsBC22TyhFtsCRnil/gEVFSHe3xQfinCIERzo/OMk6dtb5Gz86xnRlgdY5w3rogMJ2Zm0mRqh7Jn9OoEKx6frjPbgMIzZ81Hx/1qZS5RQe1wjrFQ+70ERRQcdUee/uAgKXLcGfU8nPIIhjOnHbiy7ZYGzo47QiUnSfothoSbyf/LysEai8qtDac2u+QWyJNwVkr7N3nvi9sPLGW+5u1emaMFj/uX9wHgd3xWMLA6efRPSasO6VrSboMj+1nH6Zoh3ZmhnyPZfROVfa++OAe8FChMJCcaTh6QZQWeXQWoIFGk+WufWnXICU
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cert-manager-cloudflare
    type: Opaque

