---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bazarr
  namespace: media
spec:
  chart:
    spec:
      chart: bazarr
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    env:
      TZ: Europe/Warsaw
      PUID: 1000
      PGID: 1000
    persistence:
      config:
        enabled: true
        existingClaim: "nfs-bazarr-config-pvc"
      media:
        enabled: true
        existingClaim: "nfs-media-pvc"
  interval: 10m0s

