---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jackett
  namespace: media
spec:
  chart:
    spec:
      chart: jackett
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
  values:
    env:
      TZ: Europe/Warsaw
      PUID: 1001
      PGID: 1001
    persistence:
      config:
        enabled: true
        existingClaim: "nfs-jackett-config-pvc"
  interval: 10m0s

