---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-downloads-pv
  namespace: media
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: media
    name: nfs-downloads-pvc
  nfs:
    server: 192.168.0.13
    path: "/mnt/Internal/Test/Downloads"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-downloads-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi