---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-downloads-pv
  namespace: downloads
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: downloads
    name: nfs-downloads-pvc
  storageClassName: nfs
  nfs:
    server: 192.168.0.13
    path: "/mnt/Internal/Test/Downloads"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-downloads-pvc
  namespace: downloads
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 20Gi