---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  values:
    providers:
      kubernetesCRD:
        enabled: true
        namespaces: ["default", "media"]
    additionalArguments:
      - "--certificatesresolvers.le.acme.tlschallenge"
      - "--certificatesresolvers.le.acme.email=zbigniew.zolnierowicz@gmail.com"
      - "--certificatesresolvers.le.acme.storage=/data/acme.json"
      - "--certificatesresolvers.le.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--accesslog=true"
    persistence:
      enabled: true
      existingClaim: "openebs-hostpath-traefik-certs-pvc"
      path: "/data"
    service:
      enabled: true
      type: LoadBalancer
      externalIPs:
        - 192.168.0.123
    ports:
      traefik:
        port: 9000
        expose: false
        exposedPort: 9000
        protocol: TCP
      web:
        port: 8000
        expose: true
        exposedPort: 80
        protocol: TCP
        redirectTo: websecure
      websecure:
        port: 8443
        expose: true
        exposedPort: 443
        protocol: TCP
        tls:
          enabled: true
          certResolver: le
          domains:
            - main: localhost
              sans:
                - traefik.localhost
                - torrent.localhost
                - plex.localhost
                - radarr.localhost
                - bazarr.localhost
  interval: 10m0s

