apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: traefik-routes-kustomize
  namespace: default
spec:
  interval: 5m
  path: "./routes/kustomization.yaml"
  prune: true
  sourceRef:
    kind: GitRepository
    name: traefik-crd