---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-traefik-certs-pv
  namespace: default
spec:
  capacity:
    storage: 128Mi
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: default
    name: nfs-traefik-certs-pvc
  storageClassName: nfs
  nfs:
    server: 192.168.0.13
    path: "/mnt/Internal/Test/AppData/Traefik/Certs"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-traefik-certs-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 128Mi