---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: programming
spec:
  releaseName: gitea
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://dl.gitea.io/charts/
      chart: gitea
      version: 2.1.5
      sourceRef:
        kind: HelmRepository
        name: gitea-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: sealed-secrets
      namespace: flux-system
  values:
    persistence:
      enabled: true
      existingClaim: openebs-hostpath-gitea-persistency-pvc
    ingress:
      enabled: false
    service:
      ssh:
        type: ClusterIP
        port: 22
    gitea:
      admin:
        username: "zed"
        email: "zbigniew.zolnierowicz@gmail.com"
      config:
        server:
          ROOT_URL: https://git.zolnierowi.cz
          SSH_DOMAIN: git.zolnierowi.cz
        APP_NAME: "Gitea"
        respository:
          DEFAULT_PRIVATE: true
        admin:
          DISABLE_REGULAR_ORG_CREATION: true
        security:
          PASSWORD_COMPLEXITY: "lower,upper"
          MIN_PASSWORD_LENGTH: 12
        service:
          DISABLE_REGISTRATION: true
          REQUIRE_SIGNIN_VIEW: true
        mailer:
          enabled: true
          host: smtp.sendgrid.net:465
          from: noreply@git.zolnierowi.cz
          user: apikey
          mailer_type: smtp
      database:
        builtIn:
          postgresql:
            enabled: true
    postgresql:
      persistence:
        existingClaim: openebs-hostpath-gitea-postgres-pvc
  valuesFrom:
  - kind: Secret
    name: "gitea-secret"
    valuesKey: "gitea-values"
    optional: false