---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openebs-hostpath-gitea-persistency-pvc
  namespace: programming
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openebs-hostpath-gitea-postgres-pvc
  namespace: programming
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi