apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-secret
  namespace: programming
spec:
  encryptedData:
    gitea-values: AgCXMvBJfLhAH0qJn71TV8/36QlypWD1f+S4TeyUjDMimvduI4vRCKJ/JQMh21yMKJrVmsyKlLFB+bGoUgklvASZj7mR91dt9GV04vV1hoSxruzP8IPpjV7+djjvfznLdJMSsOG+nZQ7rIgkB/uzhzmmg2NAd8LdyG7tmOf9CuWTGeiXb6bqlUE7JE/KQV+Yzuv4zwAMX2yaCdqVsPovHq5rBUSoa55CkJqTOWgM/agp6ZBlGnh9tMmIysHEKhUTbWwK1Kzzi9xMc1xFKtN3lXi1WtOJs8mHlEqV8H7gD+G9CJ66jqwlj93NFNbL1Y3L285lfLXKuCbN+YZrNbi5EpyammBDVzbZ90bwwpwqrqAFxtVSxSxd12byWs3NNXYhocO3a+7EKdsI5iH7KLvcP+wThNx9x130GSwbO4tT9oTMS2+GoPToXONX/ACesvYKmOHxDBNMReq7fnw0htysIBWhVIk/4+vBR0HPTan4X4miDetW8BBQtaoYdViwcAwMFcsHHivZAYZ7A2V1+1SyqyWu3S/PCkR4vbNeYyMXm+vbh3O+Q1xJqN1yRvlFgspINUawfW43SD1JKO0tHn42EF5bom1P1ZCUzUcbbPjSY7OxYf3q88CG8AGjWJIg161Vh8wyOn/WVi50bNKVz8OxgjEmHaeAidJ30E0jzMYSljv2zxG25eqFjOcT7YJ5gtOrOSQqcFpfUc8Y7KFLCJKZ267uSjtloCG7iGfKxw78sE6dr27yxL1uveY6Nx+H25eGn5QmtoROv2rhX88MlAVW4wU1iQh+zQhvPxrFlCfKoO8oGQuhHoJNCt3SZXRJfnyYg8nJL4WQuqGolZrX/pTzE7qOMPL76983jRJ9TuwG2O0L6FSzK7lHrEGjfJe83dExOD9mv/2Yrcxly3AJuPGidRZPPD2LhFaotCJf7teszOKhAKn0/iNK8H4CLxk=
  template:
    metadata:
      creationTimestamp: null
      name: gitea-secret
      namespace: programming

