apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-secret
  namespace: flux-system
spec:
  encryptedData:
    gitea-values: AgCM207qnQZlXv2aa/WwiNfufym2tPwB4lHyXiwX8zAaxoYItupylgjLmdo3HTuzDurjA+g2mv+T58kEDdwropLCUovoCqtYjaP8qZWwmRAu5om2YyfkFLTzwEv13hUl2ijgR3I+jD12r2xOOl23jdaeiqdczlNYmI1kW6IrIz3+GUZkSy24cGPXvUX2y+5jzTi3k54K2Z6QewnosVo+CilMhSJYsqAx0ILD+nibKS5aK+2EIz0FHVOqXs4i/ITnXdskcI4gVRChGXRMPkqBDl/upa7M49MJA29G1ZbEroo5ejRDDrngYgWcFw/YsbvATqQwbku5Rqs89t6Rn3nb/CVorlX+bf9ES60cQD7gFpE5829qV/4d8tZZbTW1155KyjftnLMaxkkurFo8w1SnYymNIGuWNW1yhpUvKUl5nLCXfypm04qmLWeiJjmedAFnihS1+UCSiGAnzji3T1F7u8mQJf5nq9bpLsujRdsUlMDvr5NJb642DRdzK5IGozvzpk+CpXRpQvinHTKwgzYq1bEmSdNxiY8leIWBgSTR8Ekm7UcRW9ueTrcxa1lrXhFHssmPXd7/jhx/ZbZq2ov2VZv/eViaOVyOzPdsYMffxFYzQAqGI1I9E+KeijSpHktuYwkfXF+aqeiIsx6Oek+BJ8j4KN0dmW6AVziVlKc9Mdl83SNUdGOuz4adQbzKrpj/g3FSOh3xw9RXRiT0ZpZOGSgl9zRINK5sGxcXYwFzA0hTtEdoJSpVcoGoow+/bn0Tols5M5FvJ6nLSEX7tAcXrgZmx067wN/YRCDCM3Qlw1SvSEGnKZ7Ek/4NfiynkeeN0IvR/rANA4E2IM9THucO3dHOywe/tpc4tjxZOIiie1HMiutWc+lZrBp1f/8oWJGXKriPPmeff6DNwraKLwX4iLjUa8z14KQgUbQnlbRjFhCJKZLpZAgtJ397HFE=
  template:
    metadata:
      creationTimestamp: null
      name: gitea-secret
      namespace: flux-system

